LBHackney-IT/notes-api

- .circleci/config.yml
> deploy to dev context missing

- NotesApi/NotesApi.csproj
- NotesApi/appsettings.json
- NotesApi/serverless.yml
- terraform/development/dynamodb.tf
- terraform/production/dynamodb.tf
- terraform/staging/dynamodb.tf
https://hackney.atlassian.net/browse/MTTL-502
The following tasks have been completed:
> Updated DynamoDb table definition

- NotesApi/Startup.cs
https://hackney.atlassian.net/browse/MTTL-595
Enabling CORS for NotesAPI
>  MTTL-595 Adding cors functionality

- NotesApi.Tests/V1/E2ETests/Steps/GetNotesSteps.cs
- NotesApi.Tests/V1/E2ETests/Stories/GetNotesByTargetIdTests.cs
- NotesApi.Tests/V1/Gateways/NotesDbGatewayTests.cs
- NotesApi/V1/Gateways/NotesDbGateway.cs
https://hackney.atlassian.net/browse/MTTL-647
Pagination token now not returned if there are no more results regardless of page size.
Deploy all the way to production.
> Fixed pagination token issue

- NotesApi/V1/Gateways/NotesDbGateway.cs
Realised there was a bug in my earlier implementation.
It was looking ahead regardless of whether or not the main search had returned a token, and if there was no token the look-ahead query was simply using an empty token meaning it was looking at the wrong thing.
The look ahead now only triggers if we got a token from the initial query.
> Get paged results bug fix

- NotesApi.Tests/V1/Boundary/Request/Validation/AuthorDetailsValidatorTests.cs
- NotesApi.Tests/V1/Domain/NoteTests.cs
- NotesApi.Tests/V1/Helper/Constants.cs
- NotesApi/V1/Boundary/Request/Validation/AuthorDetailsValidator.cs
- NotesApi/V1/Boundary/Response/NoteResponseObject.cs
- NotesApi/V1/Domain/AuthorDetails.cs
- NotesApi/V1/Gateways/NotesDbGateway.cs
https://hackney.atlassian.net/browse/MTTL-1106
Removed the Id property from the AuthorDetails.
> Removed Id from AuthorDetails

- NotesApi/NotesApi.csproj
- NotesApi/Startup.cs
https://hackney.atlassian.net/browse/MTTL-1119.
> Updated Hackney.Core package version

- CODEOWNERS
- NotesApi.Tests/V1/Boundary/Request/Validation/AuthorDetailsValidatorTests.cs
- NotesApi.Tests/V1/Domain/NoteTests.cs
- NotesApi.Tests/V1/Helper/Constants.cs
- NotesApi/NotesApi.csproj
- NotesApi/Startup.cs
- NotesApi/V1/Boundary/Request/Validation/AuthorDetailsValidator.cs
- NotesApi/V1/Boundary/Response/NoteResponseObject.cs
- NotesApi/V1/Domain/AuthorDetails.cs
- NotesApi/V1/Gateways/NotesDbGateway.cs
Release logging changes to staging
> Release mttl 1101

- NotesApi.Tests/NotesApi.Tests.csproj
- NotesApi.Tests/V1/Boundary/Request/Validation/AuthorDetailsValidatorTests.cs
- NotesApi.Tests/V1/Boundary/Request/Validation/CategorisationValidatorTests.cs
- NotesApi.Tests/V1/Boundary/Request/Validation/CreateNoteRequestValidatorTests.cs
- NotesApi.Tests/V1/E2ETests/Fixtures/NotesFixture.cs
- NotesApi.Tests/V1/E2ETests/Steps/PostNoteSteps.cs
- NotesApi.Tests/V1/E2ETests/Stories/PostNewNoteTests.cs
- NotesApi.Tests/V1/Infrastructure/FluentValidationExtensionsTests.cs
- NotesApi.Tests/V1/Infrastructure/UseErrorCodeInterceptorTests.cs
- NotesApi/Startup.cs
- NotesApi/V1/Boundary/Request/Validation/AuthorDetailsValidator.cs
- NotesApi/V1/Boundary/Request/Validation/CategorisationValidator.cs
- NotesApi/V1/Boundary/Request/Validation/CreateNoteRequestValidator.cs
- NotesApi/V1/Boundary/Request/Validation/ErrorCodes.cs
- NotesApi/V1/Infrastructure/FluentValidationExtensions.cs
- NotesApi/V1/Infrastructure/UseErrorCodeInterceptor.cs
Release MTTL-1068 changes to staging / production
> Release mttl 1068

- NotesApi/NotesApi.csproj
- NotesApi/Startup.cs
https://hackney.atlassian.net/browse/MTTL-1245
> Use individual Hackney.Core nuget packages

- .circleci/config.yml
- NotesApi/Startup.cs
- NotesApi/serverless.yml
[Jira Ticket](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-1417)
updating API to ensure that when an x-correlation-id is sent in the request
> added correlation header

- .circleci/config.yml
[Jira Ticket](https://hackney.atlassian.net/browse/MTTL-2169)
Add Nuget Context to the pipeline
> nuget context

- .circleci/config.yml
- NotesApi/serverless.yml
[JIRA ticket](https://hackney.atlassian.net/browse/MTTL-2404)
- update config.yml and serverless.yml to be enabled WAF
> Enabled WAF

- .circleci/config.yml
- NotesApi/policies/require-authorizer.js
- NotesApi/serverless.yml
[JIRA ticket](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-2422)
> Enable serverless safeguards

- .circleci/config.yml
- NotesApi.Tests/V2/Boundary/Request/Validation/CreateNoteRequestValidatorTests.cs
- NotesApi.Tests/V2/E2ETests/Fixtures/NotesFixture.cs
- NotesApi.Tests/V2/E2ETests/Stories/PostNewNoteTests.cs
- NotesApi/V2/Boundary/Request/Validation/CreateNoteRequestValidator.cs
https://hackney.atlassian.net/browse/MTTL-3171
Users raised that the character limit is too low for notes.
Double the character limit for notes to be 1000 characters.
> MTTL-3171: Update v2 character limit to be 1000 chars

- .circleci/config.yml
- NotesApi.Tests/Dockerfile
- NotesApi.Tests/NotesApi.Tests.csproj
- NotesApi.Tests/V1/Controllers/NotesApiControllerTests.cs
- NotesApi.Tests/V1/E2ETests/Stories/PostNewNoteTests.cs
- NotesApi.Tests/V1/UseCase/GetByTargetIdUseCaseTests.cs
- NotesApi.Tests/V1/UseCase/PostNewNoteUseCaseTests.cs
- NotesApi.Tests/V2/Controllers/NotesApiControllerTests.cs
- NotesApi.Tests/V2/E2ETests/Steps/PostNoteSteps.cs
- NotesApi.Tests/V2/E2ETests/Stories/PostNewNoteTests.cs
- NotesApi.Tests/V2/UseCase/GetByTargetIdUseCaseTests.cs
- NotesApi.Tests/V2/UseCase/PostNewNoteUseCaseTests.cs
- NotesApi/Dockerfile
- NotesApi/NotesApi.csproj
- NotesApi/Startup.cs
- NotesApi/V1/Controllers/BaseController.cs
- NotesApi/V2/Controllers/BaseController.cs
- NotesApi/build.cmd
- NotesApi/build.sh
- NotesApi/serverless.yml
- README.md
[MTTL-3273](https://hackney.atlassian.net/browse/MTTL-3273)
> migrate to .net6

- .circleci/config.yml
- NotesApi.Tests/Dockerfile
- NotesApi.Tests/NotesApi.Tests.csproj
- NotesApi.Tests/V1/Controllers/BaseControllerTests.cs
- NotesApi.Tests/V2/Controllers/BaseControllerTests.cs
- NotesApi.sln
- NotesApi/Dockerfile
- NotesApi/NotesApi.csproj
- NotesApi/build.cmd
- NotesApi/build.sh
- NotesApi/serverless.yml
- docker-compose.yml
https://hackney.atlassian.net/browse/HPT-604
https://hackney.atlassian.net/browse/SSI-256
Upgrade API to .NET 8.0 as 6.0 has reached end of support.
> Upgrade .NET 6.0 => 8.0

- terraform/production/main.tf
As mentioned in [PR](https://github.com/LBHackney-IT/notes-api/pull/87)
> readd terraform module

- NotesApi/serverless.yml
Update staging lambda authorizer
- Hardcode authorizer ARNs in serverless, preventing any unintended changes via parameter store
- Update staging authorizer to the new version
> Update dev and staging lambda authorizer

- NotesApi/serverless.yml
Updated production authorizer ARN
> Update production authorizer ARN
